# Generated by Django 2.2 on 2019-04-04 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190403_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 18, 56, 34, 689329), verbose_name='date published'),
        ),
    ]
