# Generated by Django 2.2 on 2019-04-04 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190403_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtutorial_title', models.CharField(max_length=200)),
                ('blogtutorial_content', models.TextField()),
                ('blogtutorial_published', models.DateTimeField(default=datetime.datetime(2019, 4, 3, 19, 36, 48, 431445), verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
