# Generated by Django 2.2 on 2019-04-04 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190403_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtutorial',
            name='blogtutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 19, 40, 13, 643567), verbose_name='date published'),
        ),
    ]
