# Generated by Django 2.2 on 2019-04-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190403_1940'),
        ('main', '0005_auto_20190403_2159'),
    ]

    operations = [
    ]
