# Generated by Django 2.2 on 2019-04-04 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190403_1946'),
        ('main', '0012_merge_20190403_1947'),
    ]

    operations = [
    ]
